'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Eggzle.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About Eggzle.
        '''</summary>
        Public Shared ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Public Shared ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm:.
        '''</summary>
        Public Shared ReadOnly Property Alarm() As String
            Get
                Return ResourceManager.GetString("Alarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto start.
        '''</summary>
        Public Shared ReadOnly Property AutoStart() As String
            Get
                Return ResourceManager.GetString("AutoStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Background color:.
        '''</summary>
        Public Shared ReadOnly Property BackgroundColor() As String
            Get
                Return ResourceManager.GetString("BackgroundColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Browse for folder....
        '''</summary>
        Public Shared ReadOnly Property BrowseForFolder() As String
            Get
                Return ResourceManager.GetString("BrowseForFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Count up.
        '''</summary>
        Public Shared ReadOnly Property CountUp() As String
            Get
                Return ResourceManager.GetString("CountUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customize and control Eggzle.
        '''</summary>
        Public Shared ReadOnly Property CustomizeAndControlEggzle() As String
            Get
                Return ResourceManager.GetString("CustomizeAndControlEggzle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Days.
        '''</summary>
        Public Shared ReadOnly Property Days() As String
            Get
                Return ResourceManager.GetString("Days", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display Format:.
        '''</summary>
        Public Shared ReadOnly Property DisplayFormat() As String
            Get
                Return ResourceManager.GetString("DisplayFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duration:.
        '''</summary>
        Public Shared ReadOnly Property Duration() As String
            Get
                Return ResourceManager.GetString("Duration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Timer.
        '''</summary>
        Public Shared ReadOnly Property EditTimer() As String
            Get
                Return ResourceManager.GetString("EditTimer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expired.
        '''</summary>
        Public Shared ReadOnly Property Expired() As String
            Get
                Return ResourceManager.GetString("Expired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export....
        '''</summary>
        Public Shared ReadOnly Property Export() As String
            Get
                Return ResourceManager.GetString("Export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export All....
        '''</summary>
        Public Shared ReadOnly Property ExportAll() As String
            Get
                Return ResourceManager.GetString("ExportAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Selected....
        '''</summary>
        Public Shared ReadOnly Property ExportSelected() As String
            Get
                Return ResourceManager.GetString("ExportSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Font:.
        '''</summary>
        Public Shared ReadOnly Property Font() As String
            Get
                Return ResourceManager.GetString("Font", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Foreground color:.
        '''</summary>
        Public Shared ReadOnly Property ForegroundColor() As String
            Get
                Return ResourceManager.GetString("ForegroundColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arguments.
        '''</summary>
        Public Shared ReadOnly Property HeaderArguments() As String
            Get
                Return ResourceManager.GetString("HeaderArguments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Command.
        '''</summary>
        Public Shared ReadOnly Property HeaderCommand() As String
            Get
                Return ResourceManager.GetString("HeaderCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event.
        '''</summary>
        Public Shared ReadOnly Property HeaderEvent() As String
            Get
                Return ResourceManager.GetString("HeaderEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Public Shared ReadOnly Property HeaderName() As String
            Get
                Return ResourceManager.GetString("HeaderName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hours.
        '''</summary>
        Public Shared ReadOnly Property Hours() As String
            Get
                Return ResourceManager.GetString("Hours", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import....
        '''</summary>
        Public Shared ReadOnly Property Import() As String
            Get
                Return ResourceManager.GetString("Import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arguments:.
        '''</summary>
        Public Shared ReadOnly Property LabelArguments() As String
            Get
                Return ResourceManager.GetString("LabelArguments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Command:.
        '''</summary>
        Public Shared ReadOnly Property LabelCommand() As String
            Get
                Return ResourceManager.GetString("LabelCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event:.
        '''</summary>
        Public Shared ReadOnly Property LabelEvent() As String
            Get
                Return ResourceManager.GetString("LabelEvent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name:.
        '''</summary>
        Public Shared ReadOnly Property LabelName() As String
            Get
                Return ResourceManager.GetString("LabelName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to License.
        '''</summary>
        Public Shared ReadOnly Property License() As String
            Get
                Return ResourceManager.GetString("License", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Look.
        '''</summary>
        Public Shared ReadOnly Property Look() As String
            Get
                Return ResourceManager.GetString("Look", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loop.
        '''</summary>
        Public Shared ReadOnly Property LoopAlarm() As String
            Get
                Return ResourceManager.GetString("LoopAlarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always On Top.
        '''</summary>
        Public Shared ReadOnly Property MenuAlwaysOnTop() As String
            Get
                Return ResourceManager.GetString("MenuAlwaysOnTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for Updates....
        '''</summary>
        Public Shared ReadOnly Property MenuCheckForUpdates() As String
            Get
                Return ResourceManager.GetString("MenuCheckForUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Compact.
        '''</summary>
        Public Shared ReadOnly Property MenuCompact() As String
            Get
                Return ResourceManager.GetString("MenuCompact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration....
        '''</summary>
        Public Shared ReadOnly Property MenuConfiguration() As String
            Get
                Return ResourceManager.GetString("MenuConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Public Shared ReadOnly Property MenuDefault() As String
            Get
                Return ResourceManager.GetString("MenuDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Timer....
        '''</summary>
        Public Shared ReadOnly Property MenuEditTimer() As String
            Get
                Return ResourceManager.GetString("MenuEditTimer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&amp;xit.
        '''</summary>
        Public Shared ReadOnly Property MenuExit() As String
            Get
                Return ResourceManager.GetString("MenuExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Full Screen.
        '''</summary>
        Public Shared ReadOnly Property MenuFullSreen() As String
            Get
                Return ResourceManager.GetString("MenuFullSreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Public Shared ReadOnly Property MenuHelp() As String
            Get
                Return ResourceManager.GetString("MenuHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help Online.
        '''</summary>
        Public Shared ReadOnly Property MenuHelpOnline() As String
            Get
                Return ResourceManager.GetString("MenuHelpOnline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Look....
        '''</summary>
        Public Shared ReadOnly Property MenuLook() As String
            Get
                Return ResourceManager.GetString("MenuLook", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Timer....
        '''</summary>
        Public Shared ReadOnly Property MenuNewTimer() As String
            Get
                Return ResourceManager.GetString("MenuNewTimer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tasks....
        '''</summary>
        Public Shared ReadOnly Property MenuTasks() As String
            Get
                Return ResourceManager.GetString("MenuTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Window.
        '''</summary>
        Public Shared ReadOnly Property MenuWindow() As String
            Get
                Return ResourceManager.GetString("MenuWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The time format you entered was unrecognized. When in doubt, use one of these formats: hours:minutes:seconds, minutes:seconds, or, simply, a number for seconds. Read the help document for more recognized formats..
        '''</summary>
        Public Shared ReadOnly Property MessageUnrecognizedTimerFormat() As String
            Get
                Return ResourceManager.GetString("MessageUnrecognizedTimerFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minutes.
        '''</summary>
        Public Shared ReadOnly Property Minutes() As String
            Get
                Return ResourceManager.GetString("Minutes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Timer.
        '''</summary>
        Public Shared ReadOnly Property NewTimer() As String
            Get
                Return ResourceManager.GetString("NewTimer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note:.
        '''</summary>
        Public Shared ReadOnly Property Note() As String
            Get
                Return ResourceManager.GetString("Note", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Public Shared ReadOnly Property Ok() As String
            Get
                Return ResourceManager.GetString("Ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause.
        '''</summary>
        Public Shared ReadOnly Property Pause() As String
            Get
                Return ResourceManager.GetString("Pause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play.
        '''</summary>
        Public Shared ReadOnly Property PlayAlarm() As String
            Get
                Return ResourceManager.GetString("PlayAlarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove.
        '''</summary>
        Public Shared ReadOnly Property Remove() As String
            Get
                Return ResourceManager.GetString("Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset.
        '''</summary>
        Public Shared ReadOnly Property Reset() As String
            Get
                Return ResourceManager.GetString("Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restarts:.
        '''</summary>
        Public Shared ReadOnly Property Restarts() As String
            Get
                Return ResourceManager.GetString("Restarts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seconds.
        '''</summary>
        Public Shared ReadOnly Property Seconds() As String
            Get
                Return ResourceManager.GetString("Seconds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Size to fit.
        '''</summary>
        Public Shared ReadOnly Property SizeToFit() As String
            Get
                Return ResourceManager.GetString("SizeToFit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Public Shared ReadOnly Property Start() As String
            Get
                Return ResourceManager.GetString("Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Public Shared ReadOnly Property StopAlarm() As String
            Get
                Return ResourceManager.GetString("StopAlarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tasks.
        '''</summary>
        Public Shared ReadOnly Property Tasks() As String
            Get
                Return ResourceManager.GetString("Tasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transparency level:.
        '''</summary>
        Public Shared ReadOnly Property TransparencyLevel() As String
            Get
                Return ResourceManager.GetString("TransparencyLevel", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
